---
- name: common configuration for all nodes
  hosts: all
  remote_user: root
  roles:
    - common

- name: deploy flapjack servers
  hosts: flapjack
  remote_user: root
  roles:
    - flapjack

- name: deploy pingbot
  hosts: flapjack
  remote_user: root
  roles:
    - pingbot
